--------------------------------------------------------
--  File created - воскресенье-мая-31-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADDRESSNUMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ADDRESSNUMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ADDRESSNUMBER_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ADDRESSNUMBER_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ADDRESSNUMBER_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ADDRESSNUMBER_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ADRESSNUMBERID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ADRESSNUMBERID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 29 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ATSTYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ATSTYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CITY_NUMBERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."CITY_NUMBERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGINSID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."LOGINSID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGINS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."LOGINS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGINS_SEQQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."LOGINS_SEQQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 23 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence LOGINS_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."LOGINS_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 181 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NUMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."NUMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 103 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NUMBERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."NUMBERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENT_SEQQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."PAYMENT_SEQQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 224 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PAYMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."PAYMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PLACETYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."PLACETYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PREFQUEUE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."PREFQUEUE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence QUEUEINTERFACE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."QUEUEINTERFACE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROLES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."ROLES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SUBSCRIBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."SUBSCRIBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SUBSCRIBER_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."SUBSCRIBER_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SUBSCRIBER_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."SUBSCRIBER_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SUBSCRIBERTYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."SUBSCRIBERTYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SUBSCSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."SUBSCSEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 224 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TELEPHONETYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."TELEPHONETYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TELEPHONETYPE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."TELEPHONETYPE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUALQUEUE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."USUALQUEUE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUALQUEUE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "C##ATS"."USUALQUEUE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADDRESSNUMBER
--------------------------------------------------------

  CREATE TABLE "C##ATS"."ADDRESSNUMBER" 
   (	"ID" NUMBER, 
	"INDX" NUMBER, 
	"NUMB" NUMBER, 
	"STREET" VARCHAR2(40 BYTE), 
	"HOME" VARCHAR2(10 BYTE), 
	"APARTMENT" NUMBER, 
	"IDTYPEPLACE" NUMBER, 
	"AREA" VARCHAR2(40 BYTE), 
	"TELTYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."ATS" 
   (	"ATSID" NUMBER, 
	"TYPEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATSATTR
--------------------------------------------------------

  CREATE TABLE "C##ATS"."ATSATTR" 
   (	"ATSTYPEID" NUMBER, 
	"ATTRNAME" VARCHAR2(30 BYTE), 
	"ATTRVAL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATSTYPE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."ATSTYPE" 
   (	"TYPEID" NUMBER, 
	"TYPENAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CITY_NUMBERS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."CITY_NUMBERS" 
   (	"NUMBERID" NUMBER, 
	"ATSID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INTERCITY_TALKS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."INTERCITY_TALKS" 
   (	"CLIENT" NUMBER, 
	"CITY" VARCHAR2(20 BYTE), 
	"CALLTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOGINS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."LOGINS" 
   (	"ID" NUMBER, 
	"LOGIN" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ISLOGGEDIN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"ROLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NUMBERS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."NUMBERS" 
   (	"NUMBERID" NUMBER, 
	"ISFREE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"NUMBR" VARCHAR2(20 BYTE), 
	"ATSID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "C##ATS"."PAYMENTS" 
   (	"ID" NUMBER, 
	"LASTPAYMENT" DATE, 
	"LASTMESSAGE" DATE, 
	"DEBT" NUMBER DEFAULT 0, 
	"MOUNTHCOST" NUMBER DEFAULT 0, 
	"INTERCITYDEBT" NUMBER DEFAULT 0, 
	"INTERCITYLASTMESSAGE" DATE, 
	"INTERCITYCALLCOST" NUMBER DEFAULT 0, 
	"MESSAGE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACETYPE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."PLACETYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREFQUEUE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."PREFQUEUE" 
   (	"ID" NUMBER, 
	"CLIENTID" NUMBER, 
	"DATA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table QUEUEINTERFACE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."QUEUEINTERFACE" 
   (	"CLIENTID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESOURCES
--------------------------------------------------------

  CREATE TABLE "C##ATS"."RESOURCES" 
   (	"CABLENUM" NUMBER DEFAULT 0, 
	"CHANNELSNUM" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "C##ATS"."ROLES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCLOGIN
--------------------------------------------------------

  CREATE TABLE "C##ATS"."SUBSCLOGIN" 
   (	"LOGIN" NUMBER, 
	"SUBSCID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIBER
--------------------------------------------------------

  CREATE TABLE "C##ATS"."SUBSCRIBER" 
   (	"ID" NUMBER, 
	"ADRESSNUMBER" NUMBER, 
	"INTERCITYENABLED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CAUSE" VARCHAR2(40 BYTE) DEFAULT '', 
	"SUBTYPEID" NUMBER, 
	"PAYMENTID" NUMBER, 
	"SERVICEENABLED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"AGE" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"SECOND_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIBERTYPE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."SUBSCRIBERTYPE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"SALE" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TELEPHONETYPE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."TELEPHONETYPE" 
   (	"TELTYPEID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"MOUNTHCOST" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUALQUEUE
--------------------------------------------------------

  CREATE TABLE "C##ATS"."USUALQUEUE" 
   (	"ID" NUMBER, 
	"CLIENTID" NUMBER, 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ATS.ADDRESSNUMBER
SET DEFINE OFF;
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('103','3880',null,'Vladimirovskaya','323','32','1','Akadem','1');
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('13','222','8','Lenina','2','22','2','Leninsky',null);
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('21','123','43','Fabric','12','11','1','Lenina','1');
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('104','6580',null,'Oktober Street','22235','545','1','South Area','3');
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('121','2357','8','Bulvar Molod.','54','33','2','Akadem',null);
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('105','8383','49','Morskoy Prospect','124','78','1','Soviet','2');
Insert into C##ATS.ADDRESSNUMBER (ID,INDX,NUMB,STREET,HOME,APARTMENT,IDTYPEPLACE,AREA,TELTYPE) values ('1','122',null,'Ivanova','12','1','2','Soviet','1');
REM INSERTING into C##ATS.ATS
SET DEFINE OFF;
Insert into C##ATS.ATS (ATSID,TYPEID) values ('2','1');
Insert into C##ATS.ATS (ATSID,TYPEID) values ('1','1');
REM INSERTING into C##ATS.ATSATTR
SET DEFINE OFF;
Insert into C##ATS.ATSATTR (ATSTYPEID,ATTRNAME,ATTRVAL) values ('1','INTERCITYCALLCOST','1');
Insert into C##ATS.ATSATTR (ATSTYPEID,ATTRNAME,ATTRVAL) values ('1','INTERCITYCOST','10');
REM INSERTING into C##ATS.ATSTYPE
SET DEFINE OFF;
Insert into C##ATS.ATSTYPE (TYPEID,TYPENAME) values ('1','USUAL');
REM INSERTING into C##ATS.CITY_NUMBERS
SET DEFINE OFF;
REM INSERTING into C##ATS.INTERCITY_TALKS
SET DEFINE OFF;
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Moskow',to_date('02.03.19','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Arch',to_date('02.03.19','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Msk',to_date('02.03.18','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Tula',to_date('01.02.18','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Krasnoyarsk',to_date('02.03.18','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','VLADIVOSTOK',to_date('22.02.20','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','VLADIVOSTOK',to_date('23.04.20','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Moskow',to_date('02.11.20','DD.MM.RR'));
Insert into C##ATS.INTERCITY_TALKS (CLIENT,CITY,CALLTIME) values ('5','Tomk',to_date('02.03.17','DD.MM.RR'));
REM INSERTING into C##ATS.LOGINS
SET DEFINE OFF;
Insert into C##ATS.LOGINS (ID,LOGIN,PASSWORD,ISLOGGEDIN,ROLE) values ('4','tester','123','N','21');
Insert into C##ATS.LOGINS (ID,LOGIN,PASSWORD,ISLOGGEDIN,ROLE) values ('1','darya','123','N','1');
Insert into C##ATS.LOGINS (ID,LOGIN,PASSWORD,ISLOGGEDIN,ROLE) values ('61','dworker','123','Y','22');
Insert into C##ATS.LOGINS (ID,LOGIN,PASSWORD,ISLOGGEDIN,ROLE) values ('3','test','13','N','21');
Insert into C##ATS.LOGINS (ID,LOGIN,PASSWORD,ISLOGGEDIN,ROLE) values ('81','tester1','123','Y','21');
REM INSERTING into C##ATS.NUMBERS
SET DEFINE OFF;
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('8','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('6','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('92','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('83','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('84','N',null,'2');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('85','N',null,'2');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('86','N',null,'2');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('7','N',null,'2');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('9','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('1','N','123','1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('43','N','4556','1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('49','N','777','1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('63','N',null,'2');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('89','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('87','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('88','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('90','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('91','N',null,'1');
Insert into C##ATS.NUMBERS (NUMBERID,ISFREE,NUMBR,ATSID) values ('93','N',null,'1');
REM INSERTING into C##ATS.PAYMENTS
SET DEFINE OFF;
Insert into C##ATS.PAYMENTS (ID,LASTPAYMENT,LASTMESSAGE,DEBT,MOUNTHCOST,INTERCITYDEBT,INTERCITYLASTMESSAGE,INTERCITYCALLCOST,MESSAGE) values ('44',to_date('05.03.20','DD.MM.RR'),null,'0','15','0',null,'1',null);
Insert into C##ATS.PAYMENTS (ID,LASTPAYMENT,LASTMESSAGE,DEBT,MOUNTHCOST,INTERCITYDEBT,INTERCITYLASTMESSAGE,INTERCITYCALLCOST,MESSAGE) values ('5',to_date('28.02.20','DD.MM.RR'),null,'10','10','0',null,'0','Првиет!
');
Insert into C##ATS.PAYMENTS (ID,LASTPAYMENT,LASTMESSAGE,DEBT,MOUNTHCOST,INTERCITYDEBT,INTERCITYLASTMESSAGE,INTERCITYCALLCOST,MESSAGE) values ('104',to_date('15.04.20','DD.MM.RR'),null,'0','0','0',null,'0',null);
Insert into C##ATS.PAYMENTS (ID,LASTPAYMENT,LASTMESSAGE,DEBT,MOUNTHCOST,INTERCITYDEBT,INTERCITYLASTMESSAGE,INTERCITYCALLCOST,MESSAGE) values ('28',to_date('05.03.20','DD.MM.RR'),null,'0','0','0',null,'0',null);
Insert into C##ATS.PAYMENTS (ID,LASTPAYMENT,LASTMESSAGE,DEBT,MOUNTHCOST,INTERCITYDEBT,INTERCITYLASTMESSAGE,INTERCITYCALLCOST,MESSAGE) values ('2',to_date('01.01.20','DD.MM.RR'),null,'0','0','0',null,'0',null);
REM INSERTING into C##ATS.PLACETYPE
SET DEFINE OFF;
Insert into C##ATS.PLACETYPE (ID,NAME) values ('2','city');
Insert into C##ATS.PLACETYPE (ID,NAME) values ('3','payphone');
Insert into C##ATS.PLACETYPE (ID,NAME) values ('1','usual');
REM INSERTING into C##ATS.PREFQUEUE
SET DEFINE OFF;
REM INSERTING into C##ATS.QUEUEINTERFACE
SET DEFINE OFF;
REM INSERTING into C##ATS.RESOURCES
SET DEFINE OFF;
REM INSERTING into C##ATS.ROLES
SET DEFINE OFF;
Insert into C##ATS.ROLES (ID,NAME) values ('1','ADMIN');
Insert into C##ATS.ROLES (ID,NAME) values ('21','USUAL');
Insert into C##ATS.ROLES (ID,NAME) values ('22','WORKER');
REM INSERTING into C##ATS.SUBSCLOGIN
SET DEFINE OFF;
Insert into C##ATS.SUBSCLOGIN (LOGIN,SUBSCID) values ('4','44');
Insert into C##ATS.SUBSCLOGIN (LOGIN,SUBSCID) values ('1','5');
Insert into C##ATS.SUBSCLOGIN (LOGIN,SUBSCID) values ('61','104');
Insert into C##ATS.SUBSCLOGIN (LOGIN,SUBSCID) values ('3','28');
REM INSERTING into C##ATS.SUBSCRIBER
SET DEFINE OFF;
Insert into C##ATS.SUBSCRIBER (ID,ADRESSNUMBER,INTERCITYENABLED,CAUSE,SUBTYPEID,PAYMENTID,SERVICEENABLED,AGE,NAME,SECOND_NAME) values ('44','105','Y',null,'1','44','Y','12','Nastya','Ivanova');
Insert into C##ATS.SUBSCRIBER (ID,ADRESSNUMBER,INTERCITYENABLED,CAUSE,SUBTYPEID,PAYMENTID,SERVICEENABLED,AGE,NAME,SECOND_NAME) values ('5','21','N','pay','1','5','Y','22','Vlad','Markov');
Insert into C##ATS.SUBSCRIBER (ID,ADRESSNUMBER,INTERCITYENABLED,CAUSE,SUBTYPEID,PAYMENTID,SERVICEENABLED,AGE,NAME,SECOND_NAME) values ('104',null,'N',null,null,'104','N','23','Mark','Tester');
Insert into C##ATS.SUBSCRIBER (ID,ADRESSNUMBER,INTERCITYENABLED,CAUSE,SUBTYPEID,PAYMENTID,SERVICEENABLED,AGE,NAME,SECOND_NAME) values ('28',null,'N',null,null,'28','N','34','Marya','Verdi');
Insert into C##ATS.SUBSCRIBER (ID,ADRESSNUMBER,INTERCITYENABLED,CAUSE,SUBTYPEID,PAYMENTID,SERVICEENABLED,AGE,NAME,SECOND_NAME) values ('1','1','N',' ','1','2','Y','12','Clad','Je');
REM INSERTING into C##ATS.SUBSCRIBERTYPE
SET DEFINE OFF;
Insert into C##ATS.SUBSCRIBERTYPE (ID,NAME,SALE) values ('1','usual','0');
Insert into C##ATS.SUBSCRIBERTYPE (ID,NAME,SALE) values ('2','beneficiary','10');
REM INSERTING into C##ATS.TELEPHONETYPE
SET DEFINE OFF;
Insert into C##ATS.TELEPHONETYPE (TELTYPEID,NAME,MOUNTHCOST) values ('1','usual','10');
Insert into C##ATS.TELEPHONETYPE (TELTYPEID,NAME,MOUNTHCOST) values ('2','parallel','5');
Insert into C##ATS.TELEPHONETYPE (TELTYPEID,NAME,MOUNTHCOST) values ('3','double','5');
REM INSERTING into C##ATS.USUALQUEUE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADDRESSNUMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."ADDRESSNUMBER_PK" ON "C##ATS"."ADDRESSNUMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESSNUMBER_UK3
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."ADDRESSNUMBER_UK3" ON "C##ATS"."ADDRESSNUMBER" ("STREET", "HOME", "APARTMENT", "AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ATSATTR_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."ATSATTR_UK1" ON "C##ATS"."ATSATTR" ("ATTRNAME", "ATSTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOGINS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."LOGINS_UK1" ON "C##ATS"."LOGINS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NUMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."NUMBERS_PK" ON "C##ATS"."NUMBERS" ("NUMBERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."PAYMENTS_PK" ON "C##ATS"."PAYMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLACETYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."PLACETYPE_PK" ON "C##ATS"."PLACETYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLACETYPE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."PLACETYPE_UK1" ON "C##ATS"."PLACETYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREFQUEUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."PREFQUEUE_PK" ON "C##ATS"."PREFQUEUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUEUEINTERFACE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."QUEUEINTERFACE_PK" ON "C##ATS"."QUEUEINTERFACE" ("CLIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUEUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."QUEUE_PK" ON "C##ATS"."USUALQUEUE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."ROLES_PK" ON "C##ATS"."ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCLOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."SUBSCLOGIN_PK" ON "C##ATS"."SUBSCLOGIN" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIBERTYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."SUBSCRIBERTYPE_PK" ON "C##ATS"."SUBSCRIBERTYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIBERTYPE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."SUBSCRIBERTYPE_UK1" ON "C##ATS"."SUBSCRIBERTYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."SUBSCRIBER_PK" ON "C##ATS"."SUBSCRIBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK" ON "C##ATS"."ATSTYPE" ("TYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK1" ON "C##ATS"."ATS" ("ATSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK2" ON "C##ATS"."TELEPHONETYPE" ("TELTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK3
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK3" ON "C##ATS"."LOGINS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TABLE1_UK1" ON "C##ATS"."ATSTYPE" ("TYPENAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TELEPHONETYPE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."TELEPHONETYPE_UK1" ON "C##ATS"."TELEPHONETYPE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUALQUEUE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##ATS"."USUALQUEUE_UK1" ON "C##ATS"."USUALQUEUE" ("CLIENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ADDRESSNUMBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."ADDRESSNUMBER_TRG" 
BEFORE INSERT ON ADDRESSNUMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."ADDRESSNUMBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDRESSNUMBER_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."ADDRESSNUMBER_TRG1" 
BEFORE INSERT ON ADDRESSNUMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."ADDRESSNUMBER_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ADDRESSNUMBER_TRG2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."ADDRESSNUMBER_TRG2" 
BEFORE INSERT ON ADDRESSNUMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."ADDRESSNUMBER_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ATSTYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."ATSTYPE_TRG" 
BEFORE INSERT ON ATSTYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TYPEID IS NULL THEN
      SELECT ATSTYPE_SEQ.NEXTVAL INTO :NEW.TYPEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."ATSTYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CITY_NUMBERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."CITY_NUMBERS_TRG" 
BEFORE INSERT ON CITY_NUMBERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."CITY_NUMBERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FINDNUMBR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."FINDNUMBR" 
before UPDATE ON SUBSCRIBER 
FOR EACH ROW
DECLARE
    cnt NUMBER := -1;
    USUALID NUMBER := -1;
    PRIVID NUMBER := -1;
    FOUND NUMBER := 0;
    TELTYPE NUMBER := -1;
    TELCOST NUMBER := -1;
    INTCOST VARCHAR2(30) := '0';
    ADDRNUM NUMBER ;
    sale number;
    totalprice number;
    CURRENTDEBT NUMBER;
    CURRENTINTERCITYDEBT NUMBER;
    INTCALLCOST VARCHAR2(30);
    prev_numbr NUMBER;
    
BEGIN
    IF :NEW.PAYMENTID != :OLD.PAYMENTID THEN
        RAISE_APPLICATION_ERROR(-20003, 'YOU COULD NOT CHANGE PAYMENT');
    END IF;

    IF :NEW.SERVICEENABLED = 'Y' AND :OLD.SERVICEENABLED = 'N' THEN
    IF :OLD.ADRESSNUMBER IS NULL THEN
        RAISE_APPLICATION_ERROR(-20003, 'ADRESS SHOULD NOT BE NULL');
    END IF;
    
    IF(:NEW.PAYMENTID IS NULL) THEN
        RAISE_APPLICATION_ERROR(-20003, 'PAYMENTID SHOULD NOT BE NULL');
    END IF;

    IF :NEW.ADRESSNUMBER IS NOT NULL THEN
        BEGIN
            SELECT TELTYPE INTO TELTYPE FROM ADDRESSNUMBER WHERE id = :NEW.ADRESSNUMBER;
            ADDRNUM := :NEW.ADRESSNUMBER;
        END;
    END IF;
    
    IF :OLD.ADRESSNUMBER IS NOT NULL THEN
        BEGIN
            SELECT TELTYPE INTO TELTYPE FROM ADDRESSNUMBER WHERE id = :OLD.ADRESSNUMBER;
            ADDRNUM := :OLD.ADRESSNUMBER;
        END;
    END IF;
    

    select NUMB into prev_numbr from addressnumber where id = addrnum;
    if(prev_numbr is null) then
    
    SELECT PAYMENTS.DEBT INTO CURRENTDEBT FROM PAYMENTS WHERE ID = :NEW.PAYMENTID; 
    SELECT payments.intercitydebt INTO CURRENTINTERCITYDEBT FROM PAYMENTS WHERE ID = :NEW.PAYMENTID; 
    IF(CURRENTDEBT > 0 OR CURRENTINTERCITYDEBT > 0) THEN 
        RAISE_APPLICATION_ERROR(-20003, 'YOU HAVE A DEBT');
    END IF;
        
    SELECT count(*) INTO cnt FROM  NUMBERS WHERE ISFREE = 'Y';
    IF cnt = 0 THEN
        SELECT ID INTO USUALID FROM subscribertype WHERE NAME = 'usual' ORDER BY ID ASC;
        SELECT ID INTO PRIVID FROM subscribertype WHERE NAME = 'beneficiary' ORDER BY ID ASC;
        
        IF :OLD.SUBTYPEID != USUALID AND :OLD.SUBTYPEID != PRIVID THEN 
            RAISE_APPLICATION_ERROR(-20003, 'COULD NOT FIND CLIENT CATHEGIRIES');
        END IF;
        
        IF :OLD.SUBTYPEID = USUALID THEN
            INSERT INTO USUALQUEUE (CLIENTID, DATA) VALUES (:NEW.ID, SYSDATE);  
        END IF;
        IF :OLD.SUBTYPEID = PRIVID THEN
            INSERT INTO PREFQUEUE (CLIENTID, DATA) VALUES (:NEW.ID, SYSDATE); 
        END IF;        
        cnt := 0;
    END IF;
    
    IF cnt > 0 THEN
        SELECT NUMBERID INTO FOUND FROM  NUMBERS WHERE ISFREE = 'Y' ORDER BY NUMBERID ASC;
        UPDATE NUMBERS SET ISFREE='N' WHERE NUMBERID = FOUND;
        UPDATE addressnumber SET NUMB = FOUND WHERE ID = :OLD.ADRESSNUMBER;
        
        SELECT ATTRVAL into INTCALLCOST FROM (((addressnumber INNER JOIN NUMBERS ON ADDRESSNUMBER.NUMB = NUMBERS.NUMBERID ) INNER JOIN ATS ON ATS.ATSID = NUMBERS.ATSID) INNER JOIN atstype ON atstype.typeid = ats.typeid) inner join atsattr on atsattr.atstypeid = atstype.typeid
        WHERE (addressnumber.id = addrnum AND ATSATTR.ATTRNAME = 'INTERCITYCALLCOST');
                
        UPDATE PAYMENTS SET INTERCITYCALLCOST = TO_NUMBER(INTCALLCOST) WHERE ID = :NEW.PAYMENTID;
    END IF;
    END IF;
    

    if :OLD.ADRESSNUMBER IS NOT NULL AND :NEW.ADRESSNUMBER IS NOT NULL then
    begin
     SELECT MOUNTHCOST INTO TELCOST FROM TELEPHONETYPE WHERE teltypeid = teltype;
     IF(:NEW.INTERCITYENABLED IS NOT NULL) THEN
        BEGIN
            IF(:NEW.INTERCITYENABLED = 'Y') THEN
                 SELECT ATTRVAL into intcost FROM (((addressnumber INNER JOIN NUMBERS ON ADDRESSNUMBER.NUMB = NUMBERS.NUMBERID ) INNER JOIN ATS ON ATS.ATSID = NUMBERS.ATSID) INNER JOIN atstype ON atstype.typeid = ats.typeid) inner join atsattr on atsattr.atstypeid = atstype.typeid
                WHERE (addressnumber.id = addrnum AND ATSATTR.ATTRNAME = 'INTERCITYCOST');
            END IF;
        END;
    END IF;
    
    select sale into sale from subscribertype where SUBSCRIBERTYPE.id = :NEW.SUBTYPEID; 
    totalprice := ((to_number(intcost) + telcost)/100)*(100 - sale);
    update payments set mounthcost = totalprice where id = :NEW.paymentid;
    end;
    
    end if;
   end if;
END;
/
ALTER TRIGGER "C##ATS"."FINDNUMBR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTNUMBER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."INSERTNUMBER" 
BEFORE INSERT ON NUMBERS 
FOR EACH ROW
DECLARE
    DPREF DATE := NULL;
    DUSUAL DATE := NULL;
    ADDRID NUMBER;
    SUBID NUMBER := -1;
BEGIN
    SELECT number_seq.NEXTVAL INTO :NEW.numberid FROM SYS.DUAL;
    if(:new.isfree = 'Y') then 
    
    SELECT MIN(DATA) INTO DPREF FROM PREFQUEUE;
    SELECT MIN(DATA) INTO DUSUAL FROM USUALQUEUE;
    
    IF((DUSUAL < DPREF AND dusual IS NOT NULL) OR DPREF IS NULL) THEN
        BEGIN
        if(DUSUAL is not null) then
            SELECT ID INTO SUBID FROM USUALQUEUE WHERE DATA = DUSUAL ORDER BY ID ASC;
        end if;
        END;
    ELSE
        BEGIN
            IF(DPREF IS NOT NULL) THEN 
                SELECT ID INTO SUBID FROM PREFQUEUE WHERE DATA = DPREF ORDER BY ID ASC;
            END IF;
        END;
    END IF;
    
    IF(dpref is not null or dusual is not null) THEN
    SELECT ADRESSNUMBER INTO ADDRID FROM SUBSCRIBER WHERE ID = SUBID;
    
    SELECT 'N' INTO :NEW.ISFREE FROM SYS.DUAL;
    
    END IF;
    
    end if;
  
    
END;
/
ALTER TRIGGER "C##ATS"."INSERTNUMBER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGINS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."LOGINS_TRG" 
BEFORE INSERT ON LOGINS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."LOGINS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGINS_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."LOGINS_TRG1" 
BEFORE INSERT ON LOGINS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT LOGINS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."LOGINS_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NUMBERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."NUMBERS_TRG" 
BEFORE INSERT ON NUMBERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."NUMBERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAYMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."PAYMENTS_TRG" 
BEFORE INSERT ON PAYMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."PAYMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLACETYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."PLACETYPE_TRG" 
BEFORE INSERT ON PLACETYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PLACETYPE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."PLACETYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREFQUEUE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."PREFQUEUE_TRG" 
BEFORE INSERT ON PREFQUEUE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."PREFQUEUE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger QUEUEINTERFACE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."QUEUEINTERFACE_TRG" 
BEFORE INSERT ON QUEUEINTERFACE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."QUEUEINTERFACE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."ROLES_TRG" 
BEFORE INSERT ON ROLES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ROLES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBSCRIBERTYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."SUBSCRIBERTYPE_TRG" 
BEFORE INSERT ON SUBSCRIBERTYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SUBSCRIBERTYPE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."SUBSCRIBERTYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TELEPHONETYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TELEPHONETYPE_TRG" 
BEFORE INSERT ON TELEPHONETYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."TELEPHONETYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TELEPHONETYPE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TELEPHONETYPE_TRG1" 
BEFORE INSERT ON TELEPHONETYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TELTYPEID IS NULL THEN
      SELECT TELEPHONETYPE_SEQ1.NEXTVAL INTO :NEW.TELTYPEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."TELEPHONETYPE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TRIGGER1" 
BEFORE INSERT ON ADDRESSNUMBER 

FOR EACH ROW 
DECLARE
   PLACE VARCHAR2(30);
BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT adressnumberid_seq.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  

    
     
END;
/
ALTER TRIGGER "C##ATS"."TRIGGER1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER2
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TRIGGER2" 
AFTER INSERT ON LOGINS 
FOR EACH ROW
DECLARE
    PAYID NUMBER := 0;
    SUBSCRIBERID NUMBER := 0;

BEGIN
  PAYID := payment_seqq.NEXTVAL;
  SUBSCRIBERID := subscseq.NEXTVAL;

  INSERT INTO payments (ID, LASTPAYMENT) VALUES (PAYID, SYSDATE);
  INSERT INTO SUBSCRIBER (ID, PAYMENTID) VALUES (SUBSCRIBERID, PAYID);
  INSERT INTO SUBSCLOGIN (LOGIN, SUBSCID) VALUES (:New.ID, SUBSCRIBERID);
END;
/
ALTER TRIGGER "C##ATS"."TRIGGER2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER3
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TRIGGER3" 
BEFORE UPDATE ON LOGINS
FOR EACH ROW
DECLARE
    PAYMENTDATE DATE;
    PAYMENTSTR VARCHAR2(30);
    CURYEAR VARCHAR(5);
    CURRENTDATE DATE;
    paym number;
BEGIN
    SELECT (SYSDATE) INTO CURRENTDATE FROM DUAL;
    select to_char(CURRENTDATE, 'YYYY') INTO CURYEAR from dual;
    PAYMENTSTR := CONCAT('20', CONCAT('.', CONCAT(to_char( CURRENTDATE, 'mm'), CONCAT('.', CURYEAR))));
    PAYMENTDATE := TO_DATE(PAYMENTSTR);
          
    update payments set debt = (debt + mounthcost) where lastpayment > PAYMENTDATE; 
    UPDATE (SELECT SUBSCRIBER.serviceenabled as se, payments.debt as de from subscriber inner JOIN payments on subscriber.paymentid = payments.id 
        where payments.debt > 0 AND payments.lastmessage IS NOT NULL AND (CURRENTDATE > (payments.lastmessage + 2))) t SET t.se = 'N';
        
     UPDATE payments  SET payments.debt = (payments.debt + 0.3 * payments.debt) where payments.lastmessage IS NOT NULL AND (CURRENTDATE > (payments.lastmessage + 2));
        
    UPDATE payments SET payments.intercitydebt = (payments.intercitydebt + 0.3 *payments.intercitydebt)
        where payments.intercitydebt > 0 AND payments.intercitylastmessage IS NOT NULL AND (CURRENTDATE > (payments.intercitylastmessage + 2));    
END;
/
ALTER TRIGGER "C##ATS"."TRIGGER3" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER4
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."TRIGGER4" 
AFTER INSERT ON NUMBERS 
FOR EACH ROW
DECLARE
    DPREF DATE := NULL;
    DUSUAL DATE := NULL;
    ADDRID NUMBER;
    SUBID NUMBER := -1;

BEGIN
  if(:new.numbr is not null) then 
    
    SELECT MIN(DATA) INTO DPREF FROM PREFQUEUE;
    SELECT MIN(DATA) INTO DUSUAL FROM USUALQUEUE;
    
    IF((DUSUAL < DPREF AND dusual IS NOT NULL) OR DPREF IS NULL) THEN
        BEGIN
            if(DUSUAL is not null) then
            SELECT clientid INTO SUBID FROM USUALQUEUE WHERE DATA = DUSUAL ORDER BY ID ASC;
            DELETE from USUALQUEUE where clientid = subid;
            end if;
        END;
    ELSE
        BEGIN
            IF(DPREF IS NOT NULL) THEN 
                SELECT clientid INTO SUBID FROM PREFQUEUE WHERE DATA = DPREF ORDER BY ID ASC;
                DELETE from USUALQUEUE where clientid = subid;
            END IF;
        END;
    END IF;
    
    IF(dpref is not null or dusual is not null) THEN
    SELECT ADRESSNUMBER INTO ADDRID FROM SUBSCRIBER WHERE ID = SUBID;
    UPDATE ADDRESSNUMBER SET NUMB = :NEW.NUMBERID WHERE ID = ADDRID;    
    update subscriber set serviceenabled = 'Y' where id = subid;
    
    END IF;
    
    end if;
    
END;
/
ALTER TRIGGER "C##ATS"."TRIGGER4" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDADDRCHECK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."UPDADDRCHECK" 
BEFORE UPDATE ON ADDRESSNUMBER 
FOR EACH ROW 
DECLARE
    USUALID NUMBER := -1;
    DOUBLEID NUMBER := -1;
    PARALLELID NUMBER := -1;
    USUALPLACEID NUMBER := -1;
    CNT NUMBER := -1;
BEGIN
    SELECT ID INTO USUALPLACEID FROM PLACETYPE WHERE NAME = 'usual';


    SELECT TELTYPEID INTO USUALID FROM TELEPHONETYPE WHERE NAME = 'usual' order by teltypeid ASC;
    SELECT TELTYPEID INTO DOUBLEID FROM TELEPHONETYPE WHERE NAME = 'double' order by teltypeid ASC;
    SELECT TELTYPEID INTO parallelid FROM TELEPHONETYPE WHERE NAME = 'parallel' order by teltypeid ASC;
  
    IF :NEW.TELTYPE = DOUBLEID AND :OLD.TELTYPE = PARALLELID THEN
        RAISE_APPLICATION_ERROR(-20003, 'IT IS ALREADY PARALLEL');
    END IF;
  
    IF :NEW.TELTYPE = USUALID AND (:OLD.TELTYPE = DOUBLEID  OR :OLD.TELTYPE = PARALLELID) THEN
        SELECT COUNT(*) INTO CNT FROM subscriber WHERE ADRESSNUMBER = :OLD.ID;
        IF CNT > 1 THEN 
            RAISE_APPLICATION_ERROR(-20003, 'YOU COULD NOT DISCONNECT OTHER PEOPLE, CHANGE ADDRESS OR TURL SERVOCE OFF');
        END IF;
    END IF;
END;
/
ALTER TRIGGER "C##ATS"."UPDADDRCHECK" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUALQUEUE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."USUALQUEUE_TRG" 
BEFORE INSERT ON USUALQUEUE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."USUALQUEUE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUALQUEUE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##ATS"."USUALQUEUE_TRG1" 
BEFORE INSERT ON USUALQUEUE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USUALQUEUE_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##ATS"."USUALQUEUE_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGINS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."LOGINS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."LOGINS" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."LOGINS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."LOGINS" ADD CONSTRAINT "TABLE11_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK3" ON "C##ATS"."LOGINS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "C##ATS"."LOGINS" MODIFY ("ISLOGGEDIN" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."LOGINS" ADD CONSTRAINT "LOGINS_CHK1" CHECK (ISLOGGEDIN = 'N' OR ISLOGGEDIN = 'Y') ENABLE;
  ALTER TABLE "C##ATS"."LOGINS" ADD CONSTRAINT "LOGINS_UK1" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("LASTPAYMENT" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("DEBT" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("MOUNTHCOST" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" ADD CONSTRAINT "PAYMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."PAYMENTS" ADD CONSTRAINT "PAYMENTS_CHK2" CHECK (MOUNTHCOST > 0 OR MOUNTHCOST = 0) ENABLE;
  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("INTERCITYDEBT" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" ADD CONSTRAINT "PAYMENTS_CHK3" CHECK (INTERCITYDEBT > 0 OR INTERCITYDEBT = 0) ENABLE;
  ALTER TABLE "C##ATS"."PAYMENTS" MODIFY ("INTERCITYCALLCOST" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PAYMENTS" ADD CONSTRAINT "PAYMENTS_CHK4" CHECK (INTERCITYCALLCOST > 0 OR INTERCITYCALLCOST = 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table CITY_NUMBERS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."CITY_NUMBERS" MODIFY ("NUMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."CITY_NUMBERS" MODIFY ("ATSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INTERCITY_TALKS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."INTERCITY_TALKS" MODIFY ("CLIENT" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."INTERCITY_TALKS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."INTERCITY_TALKS" MODIFY ("CALLTIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "C##ATS"."SUBSCRIBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBER" MODIFY ("INTERCITYENABLED" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBER" MODIFY ("PAYMENTID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_CHK3" CHECK (AGE >= 0) ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBER" MODIFY ("SERVICEENABLED" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_CHK1" CHECK (serviceenabled = 'N' or serviceenabled = 'Y') ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_CHK2" CHECK (INTERCITYENABLED = 'N' OR INTERCITYENABLED = 'Y') ENABLE;
--------------------------------------------------------
--  Constraints for Table ATS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ATS" MODIFY ("ATSID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATS" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATS" ADD CONSTRAINT "ATS_PK" PRIMARY KEY ("ATSID")
  USING INDEX (CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK1" ON "C##ATS"."ATS" ("ATSID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLACETYPE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."PLACETYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PLACETYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PLACETYPE" ADD CONSTRAINT "PLACETYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."PLACETYPE" ADD CONSTRAINT "PLACETYPE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ROLES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ROLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "C##ATS"."RESOURCES" MODIFY ("CABLENUM" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."RESOURCES" MODIFY ("CHANNELSNUM" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."RESOURCES" ADD CONSTRAINT "RESOURCES_CHK1" CHECK (CHANNELSNUM > 0) ENABLE;
  ALTER TABLE "C##ATS"."RESOURCES" ADD CONSTRAINT "RESOURCES_CHK3" CHECK (CABLENUM > 0) ENABLE;
--------------------------------------------------------
--  Constraints for Table NUMBERS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."NUMBERS" MODIFY ("NUMBERID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."NUMBERS" ADD CONSTRAINT "NUMBERS_PK" PRIMARY KEY ("NUMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."NUMBERS" ADD CONSTRAINT "NUMBERS_CHK1" CHECK (REGEXP_LIKE(NUMBR, '^(\+)?[0-9]+$')) ENABLE;
  ALTER TABLE "C##ATS"."NUMBERS" ADD CONSTRAINT "NUMBERS_CHK2" CHECK (ISFREE = 'N' OR ISFREE = 'Y') ENABLE;
  ALTER TABLE "C##ATS"."NUMBERS" MODIFY ("ATSID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCLOGIN
--------------------------------------------------------

  ALTER TABLE "C##ATS"."SUBSCLOGIN" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCLOGIN" MODIFY ("SUBSCID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCLOGIN" ADD CONSTRAINT "SUBSCLOGIN_PK" PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATSATTR
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ATSATTR" MODIFY ("ATSTYPEID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATSATTR" MODIFY ("ATTRNAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATSATTR" MODIFY ("ATTRVAL" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATSATTR" ADD CONSTRAINT "ATSATTR_UK1" UNIQUE ("ATTRNAME", "ATSTYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUALQUEUE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."USUALQUEUE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."USUALQUEUE" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."USUALQUEUE" ADD CONSTRAINT "QUEUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."USUALQUEUE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."USUALQUEUE" ADD CONSTRAINT "USUALQUEUE_UK1" UNIQUE ("CLIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREFQUEUE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."PREFQUEUE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PREFQUEUE" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."PREFQUEUE" ADD CONSTRAINT "PREFQUEUE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."PREFQUEUE" MODIFY ("DATA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIBERTYPE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" MODIFY ("SALE" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" ADD CONSTRAINT "SUBSCRIBERTYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" ADD CONSTRAINT "SUBSCRIBERTYPE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBERTYPE" ADD CONSTRAINT "SUBSCRIBERTYPE_CHK1" CHECK (sale < 100 AND sale > -1) ENABLE;
--------------------------------------------------------
--  Constraints for Table QUEUEINTERFACE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."QUEUEINTERFACE" MODIFY ("CLIENTID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."QUEUEINTERFACE" ADD CONSTRAINT "QUEUEINTERFACE_PK" PRIMARY KEY ("CLIENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TELEPHONETYPE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."TELEPHONETYPE" MODIFY ("TELTYPEID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."TELEPHONETYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."TELEPHONETYPE" MODIFY ("MOUNTHCOST" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."TELEPHONETYPE" ADD CONSTRAINT "TEL_PK" PRIMARY KEY ("TELTYPEID")
  USING INDEX (CREATE UNIQUE INDEX "C##ATS"."TABLE1_PK2" ON "C##ATS"."TELEPHONETYPE" ("TELTYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "C##ATS"."TELEPHONETYPE" ADD CONSTRAINT "TELEPHONETYPE_UK1" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESSNUMBER
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("INDX" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("HOME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("APARTMENT" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("IDTYPEPLACE" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" ADD CONSTRAINT "ADDRESSNUMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" MODIFY ("AREA" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" ADD CONSTRAINT "ADDRESSNUMBER_UK3" UNIQUE ("STREET", "HOME", "APARTMENT", "AREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATSTYPE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ATSTYPE" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATSTYPE" MODIFY ("TYPENAME" NOT NULL ENABLE);
  ALTER TABLE "C##ATS"."ATSTYPE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("TYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ATS"."ATSTYPE" ADD CONSTRAINT "TABLE1_UK1" UNIQUE ("TYPENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDRESSNUMBER
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ADDRESSNUMBER" ADD CONSTRAINT "ADDRESSNUMBER_FK1" FOREIGN KEY ("IDTYPEPLACE")
	  REFERENCES "C##ATS"."PLACETYPE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" ADD CONSTRAINT "ADDRESSNUMBER_FK3" FOREIGN KEY ("TELTYPE")
	  REFERENCES "C##ATS"."TELEPHONETYPE" ("TELTYPEID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ATS"."ADDRESSNUMBER" ADD CONSTRAINT "ADDRESSNUMBER_FK2" FOREIGN KEY ("NUMB")
	  REFERENCES "C##ATS"."NUMBERS" ("NUMBERID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ATS" ADD CONSTRAINT "TABLE1_FK1" FOREIGN KEY ("TYPEID")
	  REFERENCES "C##ATS"."ATSTYPE" ("TYPEID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATSATTR
--------------------------------------------------------

  ALTER TABLE "C##ATS"."ATSATTR" ADD CONSTRAINT "ATSATTR_FK1" FOREIGN KEY ("ATSTYPEID")
	  REFERENCES "C##ATS"."ATSTYPE" ("TYPEID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CITY_NUMBERS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."CITY_NUMBERS" ADD CONSTRAINT "CITY_NUMBERS_FK1" FOREIGN KEY ("ATSID")
	  REFERENCES "C##ATS"."ATS" ("ATSID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INTERCITY_TALKS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."INTERCITY_TALKS" ADD CONSTRAINT "INTERCITY_TALKS_FK1" FOREIGN KEY ("CLIENT")
	  REFERENCES "C##ATS"."SUBSCRIBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOGINS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."LOGINS" ADD CONSTRAINT "LOGINS_FK1" FOREIGN KEY ("ROLE")
	  REFERENCES "C##ATS"."ROLES" ("ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NUMBERS
--------------------------------------------------------

  ALTER TABLE "C##ATS"."NUMBERS" ADD CONSTRAINT "NUMBERS_FK1" FOREIGN KEY ("ATSID")
	  REFERENCES "C##ATS"."ATS" ("ATSID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREFQUEUE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."PREFQUEUE" ADD CONSTRAINT "PREFQUEUE_FK1" FOREIGN KEY ("CLIENTID")
	  REFERENCES "C##ATS"."SUBSCRIBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCLOGIN
--------------------------------------------------------

  ALTER TABLE "C##ATS"."SUBSCLOGIN" ADD CONSTRAINT "SUBSCLOGIN_FK2" FOREIGN KEY ("SUBSCID")
	  REFERENCES "C##ATS"."SUBSCRIBER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ATS"."SUBSCLOGIN" ADD CONSTRAINT "SUBSCLOGIN_FK1" FOREIGN KEY ("LOGIN")
	  REFERENCES "C##ATS"."LOGINS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIBER
--------------------------------------------------------

  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_FK1" FOREIGN KEY ("ADRESSNUMBER")
	  REFERENCES "C##ATS"."ADDRESSNUMBER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_FK2" FOREIGN KEY ("PAYMENTID")
	  REFERENCES "C##ATS"."PAYMENTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##ATS"."SUBSCRIBER" ADD CONSTRAINT "SUBSCRIBER_FK3" FOREIGN KEY ("SUBTYPEID")
	  REFERENCES "C##ATS"."SUBSCRIBERTYPE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUALQUEUE
--------------------------------------------------------

  ALTER TABLE "C##ATS"."USUALQUEUE" ADD CONSTRAINT "USUALQUEUE_FK1" FOREIGN KEY ("CLIENTID")
	  REFERENCES "C##ATS"."SUBSCRIBER" ("ID") ON DELETE CASCADE ENABLE;
